### PR TITLE
Only allow transit routes with at least two stops

### LINKED ISSUE #128: Undefinied time caused by faulty transit schedule
In particular cases, e.g. due to spatial filtering of a gtfs feed, it could happen, that trip.getStopTimes() delivers less than 2 stops.
2 Stops are at least required in order to calculate offsets between stops. Otherwise the resulting schedule will provide a transit route with 1 stop that has no offsets. A stop with no arrival and no departure offset causes a undefinied time exception in matsim13 when using sbb pt router.

Thus we should think on changing this code to:

https://github.com/matsim-org/pt2matsim/blob/master/src/main/java/org/matsim/pt2matsim/gtfs/GtfsConverter.java
Method: createTransitRoute

```
Old:
		if(trip.getStopTimes().size() == 0) {
			noStopTimeTrips++;
			return null;
		}`
New:
		if(trip.getStopTimes().size() >= 2) {
			noStopTimeTrips++;
			return null;
		}`

```

### PR DESCRIPTION
**Pull request by steffenaxer**
Fixes #128

### CODE REVIEW

File: src/main/java/org/matsim/pt2matsim/gtfs/GtfsConverter.java [hunk 1]
```diff
@@ -223,7 +223,7 @@ protected TransitLine createTransitLine(Route gtfsRoute) {
 	protected TransitRoute createTransitRoute(Trip trip, Map<Id<TransitStopFacility>, TransitStopFacility> stopFacilities) {
 		Id<RouteShape> shapeId = trip.getShape() != null ? trip.getShape().getId() : null;
 
-		if(trip.getStopTimes().size() == 0) {
+		if(trip.getStopTimes().size() >= 2) {
```
Comment (polettif) [inline src/main/java/org/matsim/pt2matsim/gtfs/GtfsConverter.java:226]: Sorry, I didn't look at this properly. It should be `<= 1` since the method returns null if a trip is unusable. We want to keep going if there are more than 2 stops.

**Review by polettif — CHANGES_REQUESTED** [review]

File: src/main/java/org/matsim/pt2matsim/gtfs/GtfsConverter.java (hunk 1 above)
Comment (steffenaxer) [reply src/main/java/org/matsim/pt2matsim/gtfs/GtfsConverter.java:226]: yes, you are right... Didn't change it correctly. Sorry. I also meant <= 1

Comment (steffenaxer) [reply src/main/java/org/matsim/pt2matsim/gtfs/GtfsConverter.java:226]: Didn't we need at least 2 stops in order to calculate offsets

Comment (polettif) [reply src/main/java/org/matsim/pt2matsim/gtfs/GtfsConverter.java:226]: Well, we need at least 2 stops in a trip to create a transit route. This if clause however returns with null from `createTransitRoute` if there are not enough stops (i.e. 0 or only 1 stop). The original clause only considered trips without stops, we want it to consider trips with 0 or 1 stop.

Comment (steffenaxer) [reply src/main/java/org/matsim/pt2matsim/gtfs/GtfsConverter.java:226]: I agree, so`<= 1` should be fine. Should I provide a 2nd pull request with this solution?

Comment (polettif) [reply src/main/java/org/matsim/pt2matsim/gtfs/GtfsConverter.java]: Yes, it's cleaner that way. Thank you.

**Review by steffenaxer — COMMENTED** [review]
I agree this change. Sorry I am a novice in git :)

**Comment by polettif** [comment]
> I agree this change. Sorry I am a novice in git :)

No worries, we've all been there :) I'll squash the commit upon merging. Thanks again.
